export const COMMON_WORDS = [
  // "ross",
  // "monica",
  // "geller",
  // "chandler",
  // "bing",
  // "joey",
  // "tribbiani",
  // "phoebe",
  // "buffay",
  // "rachel",
  // "green",
  "the",
  "be",
  "to",
  "from",
  "of",
  "and",
  "a",
  "in",
  "this",
  "that",
  "have",
  "i",
  "it",
  "for",
  "not",
  "on",
  "as",
  "you",
  "do",
  "at",
  "but",
  "by",
  "we",
  "they",
  "he",
  "she",
  "or",
  "an",
  "one",
  "d",
  "m",
  "s",
  "ll",
  "t",
  "ve",
  "re",
];

export const EPISODE_NAMES = new Map([
  ["s01_e01", "The One Where Monica Gets a Roommate"],
  ["s01_e02", "The One With the Sonogram at the End"],
  ["s01_e03", "The One With the Thumb"],
  ["s01_e04", "The One With George Stephanopoulos"],
  ["s01_e05", "The One With the East German Laundry Detergent"],
  ["s01_e06", "The One With the Butt"],
  ["s01_e07", "The One With the Blackout"],
  ["s01_e08", "The One Where Nana Dies Twice"],
  ["s01_e09", "The One Where Underdog Gets Away"],
  ["s01_e10", "The One With the Monkey"],
  ["s01_e11", "The One With Mrs. Bing"],
  ["s01_e12", "The One With the Dozen Lasagnas"],
  ["s01_e13", "The One With the Boobies"],
  ["s01_e14", "The One With the Candy Hearts"],
  ["s01_e15", "The One With the Stoned Guy"],
  ["s01_e16", "The One With Two Parts, Part 1"],
  ["s01_e17", "The One With Two Parts, Part 2"],
  ["s01_e18", "The One With All the Poker"],
  ["s01_e19", "The One Where the Monkey Gets Away"],
  ["s01_e20", "The One with the Evil Orthodontist"],
  ["s01_e21", "The One with Fake Monica"],
  ["s01_e22", "The One with the Ick Factor"],
  ["s01_e23", "The One with the Birth"],
  ["s01_e24", "The One where Rachel Finds Out"],
  ["s02_e01", "The One With Ross' New Girlfriend"],
  ["s02_e02", "The One With the Breast Milk"],
  ["s02_e03", "The One Where Heckles Dies"],
  ["s02_e04", "The One With Phoebe's Husband"],
  ["s02_e05", "The One With Five Steaks and an Eggplant"],
  ["s02_e06", "The One With the Baby on the Bus"],
  ["s02_e07", "The One Where Ross Finds Out"],
  ["s02_e08", "The One With the List"],
  ["s02_e09", "The One With Phoebe's Dad"],
  ["s02_e10", "The One With Russ"],
  ["s02_e11", "The One With The Lesbian Wedding"],
  ["s02_e12", "The One After the Superbowl, Part 1"],
  ["s02_e13", "The One After the Superbowl, Part 2"],
  ["s02_e14", "The One With The Prom Video"],
  ["s02_e15", "The One Where Ross and RachelYou Know"],
  ["s02_e16", "The One Where Joey Moves Out"],
  ["s02_e17", "The One Where Eddie Moves In"],
  ["s02_e18", "The One Where Dr Ramoray Dies"],
  ["s02_e19", "The One Where Eddie Won't Go"],
  ["s02_e20", "The One Where Old Yeller Dies"],
  ["s02_e21", "The One With The Bullies"],
  ["s02_e22", "The One With Two Parties"],
  ["s02_e23", "The One With The Chicken Pox"],
  ["s02_e24", "The One With Barry & Mindy's Wedding"],
  ["s03_e01", "The One With The Princess Leia Fantasy"],
  ["s03_e02", "The One Where No One's Ready"],
  ["s03_e03", "The One With The Jam"],
  ["s03_e04", "The One With The Metaphorical Tunnel"],
  ["s03_e05", "The One With Frank, Jr"],
  ["s03_e06", "The One With The Flashback"],
  ["s03_e07", "The One With The Racecar Bed"],
  ["s03_e08", "The One With The Giant Poking Device"],
  ["s03_e09", "The One With The Football"],
  ["s03_e10", "The One Where Rachel Quits"],
  ["s03_e11", "The One Where Chandler Can't Remember Which Sister"],
  ["s03_e12", "The One With All The Jealousy"],
  ["s03_e13", "The One Where Monica and Richard Are Just Friends"],
  ["s03_e14", "The One With Phoebe's Ex-Partner"],
  ["s03_e15", "The One Where Ross And Rachel Take A Break"],
  ["s03_e16", "The One The Morning After"],
  ["s03_e17", "The One Without The Ski Trip"],
  ["s03_e18", "The One With The Hypnosis Tape"],
  ["s03_e19", "The One With The Tiny T-Shirt"],
  ["s03_e20", "The One With The Dollhouse"],
  ["s03_e21", "The One With a Chick And a Duck"],
  ["s03_e22", "The One With The Screamer"],
  ["s03_e23", "The One With Ross's Thing"],
  ["s03_e24", "The One With The Ultimate Fighting Champion"],
  ["s03_e25", "The One At The Beach"],
  ["s04_e01", "The One With The Jellyfish"],
  ["s04_e02", "The One With The Cat"],
  ["s04_e03", "The One With The 'Cuffs"],
  ["s04_e04", "The One With The Ballroom Dancing"],
  ["s04_e05", "The One With Joey's New Girlfriend"],
  ["s04_e06", "The One With The Dirty Girl"],
  ["s04_e07", "The One Where Chandler Crosses The Line"],
  ["s04_e08", "The One With Chandler In A Box"],
  ["s04_e09", "The One Where They're Going To PARTY!"],
  ["s04_e10", "The One With The Girl From Poughkeepsie"],
  ["s04_e11", "The One With Phoebe's Uterus"],
  ["s04_e12", "The One With The Embryos"],
  ["s04_e13", "The One With Rachel's Crush"],
  ["s04_e14", "The One With Joey's Dirty Day"],
  ["s04_e15", "The One With All The Rugby"],
  ["s04_e16", "The One With The Fake Party"],
  ["s04_e17", "The One With The Free Porn"],
  ["s04_e18", "The One With Rachel's New Dress"],
  ["s04_e19", "The One With All The Haste"],
  ["s04_e20", "The One With All The Wedding Dresses"],
  ["s04_e21", "The One With The Invitation"],
  ["s04_e22", "The One With The Worst Best Man Ever"],
  ["s04_e23", "The One With Ross's Wedding, Part 1"],
  ["s04_e24", "The One With Ross's Wedding, Part 2"],
  ["s05_e01", "The One After Ross Says Rachel"],
  ["s05_e02", "The One With All The Kissing"],
  ["s05_e03", "The One With The Triplets"],
  ["s05_e04", "The One Where Phoebe Hates PBS"],
  ["s05_e05", "The One With The Kips"],
  ["s05_e06", "The One With The Yeti"],
  ["s05_e07", "The One Where Ross Moves In"],
  ["s05_e08", "The One With All The Thanksgivings"],
  ["s05_e09", "The One With Ross's Sandwich"],
  ["s05_e10", "The One With The Inappropriate Sister"],
  ["s05_e11", "The One With All The Resolutions"],
  ["s05_e12", "The One With Chandler's Work Laugh"],
  ["s05_e13", "The One With Joey's Bag"],
  ["s05_e14", "The One Where Everybody Finds Out"],
  ["s05_e15", "The One With The Girl Who Hits Joey"],
  ["s05_e16", "The One With The Cop"],
  ["s05_e17", "The One With Rachel's Inadvertent Kiss"],
  ["s05_e18", "The One Where Rachel Smokes"],
  ["s05_e19", "The One Where Ross Can't Flirt"],
  ["s05_e20", "The One With The Ride-Along"],
  ["s05_e21", "The One With The Ball"],
  ["s05_e22", "The One With Joey's Big Break"],
  ["s05_e23", "The One In Vegas, Part 1"],
  ["s05_e24", "The One In Vegas, Part 2"],
  ["s06_e01", "The One After Vegas"],
  ["s06_e02", "The One Where Ross Hugs Rachel"],
  ["s06_e03", "The One With Ross's Denial"],
  ["s06_e04", "The One Where Joey Loses His Insurance"],
  ["s06_e05", "The One With Joey's Porsche"],
  ["s06_e06", "The One On The Last Night"],
  ["s06_e07", "The One Where Phoebe Runs"],
  ["s06_e08", "The One With Ross's Teeth"],
  ["s06_e09", "The One Where Ross Got High"],
  ["s06_e10", "The One With The Routine"],
  ["s06_e11", "The One With The Apothecary Table"],
  ["s06_e12", "The One With The Joke"],
  ["s06_e13", "The One With Rachel's Sister"],
  ["s06_e14", "The One Where Chandler Can't Cry"],
  ["s06_e15", "The One That Could Have Been, Part 1"],
  ["s06_e16", "The One That Could Have Been, Part 2"],
  ["s06_e17", "The One With Unagi"],
  ["s06_e18", "The One Where Ross Dates a Student"],
  ["s06_e19", "The One With Joey's Fridge"],
  ["s06_e20", "The One With Mac & C.H.E.E.S.E."],
  ["s06_e21", "The One Where Ross Meets Elizabeth's Dad"],
  ["s06_e22", "The One Where Paul's The Man"],
  ["s06_e23", "The One With The Ring"],
  ["s06_e24", "The One With The Proposal, Part 1"],
  ["s06_e25", "The One With The Proposal, Part 2"],
  ["s07_e01", "The One With Monica's Thunder"],
  ["s07_e02", "The One With Rachel's Book"],
  ["s07_e03", "The One With Phoebe's Cookies"],
  ["s07_e04", "The One With Rachel's Assistant"],
  ["s07_e05", "The One With The Engagement Picture"],
  ["s07_e06", "The One With The Nap Partners"],
  ["s07_e07", "The One With Ross's Library Book"],
  ["s07_e08", "The One Where Chandler Doesn't Like Dogs"],
  ["s07_e09", "The One With All The Candy"],
  ["s07_e10", "The One With the Holiday Armadillo"],
  ["s07_e11", "The One With All The Cheesecakes"],
  ["s07_e12", "The One Where They're Up All Night"],
  ["s07_e13", "The One Where Rosita Dies"],
  ["s07_e14", "The One Where They All Turn Thirty"],
  ["s07_e15", "The One With Joey's New Brain"],
  ["s07_e16", "The One With The Truth About London"],
  ["s07_e17", "The One With The Cheap Wedding Dress"],
  ["s07_e18", "The One With Joey's Award"],
  ["s07_e19", "The One With Ross and Monica's Cousin"],
  ["s07_e20", "The One With Rachel's Big Kiss"],
  ["s07_e21", "The One With The Vows"],
  ["s07_e22", "The One With Chandler's Dad"],
  ["s07_e23", "The One With Monica and Chandler's Wedding, Part 1"],
  ["s07_e24", "The One With Monica and Chandler's Wedding, Part 2"],
  ["s08_e01", 'The One After "I Do"'],
  ["s08_e02", "The One With The Red Sweater"],
  ["s08_e03", "The One Where Rachel Tells"],
  ["s08_e04", "The One With The Video Tape"],
  ["s08_e05", "The One With Rachel's Date"],
  ["s08_e06", "The One With The Halloween Party"],
  ["s08_e07", "The One With The Stain"],
  ["s08_e08", "The One With The Stripper"],
  ["s08_e09", "The One With The Rumor"],
  ["s08_e10", "The One With Monica's Boots"],
  ["s08_e11", "The One With Ross' Step Forward"],
  ["s08_e12", "The One Where Joey Dates Rachel"],
  ["s08_e13", "The One Where Chandler Takes a Bath"],
  ["s08_e14", "The One With The Secret Closet"],
  ["s08_e15", "The One With The Birthing Video"],
  ["s08_e16", "The One Where Joey Tells Rachel"],
  ["s08_e17", "The One With The Tea Leaves"],
  ["s08_e18", "The One In Massapequa"],
  ["s08_e19", "The One With Joey's Interview"],
  ["s08_e20", "The One With The Baby Shower"],
  ["s08_e21", "The One With The Cooking Class"],
  ["s08_e22", "The One Where Rachel is Late"],
  ["s08_e23", "The One Where Rachel Has a Baby, Part 1"],
  ["s08_e24", "The One Where Rachel Has a Baby, Part 2"],
  ["s09_e01", "The One Where No One Proposes"],
  ["s09_e02", "The One Where Emma Cries"],
  ["s09_e03", "The One With the Pediatrician"],
  ["s09_e04", "The One With the Sharks"],
  ["s09_e05", "The One With Phoebe's Birthday Dinner"],
  ["s09_e06", "The One With the Male Nanny"],
  ["s09_e07", "The One With Ross's Inappropriate Song"],
  ["s09_e08", "The One With Rachel's Other Sister"],
  ["s09_e09", "The One With Rachel's Phone Number"],
  ["s09_e10", "The One With Christmas in Tulsa"],
  ["s09_e11", "The One Where Rachel Goes Back To Work"],
  ["s09_e12", "The One With Phoebe's Rats"],
  ["s09_e13", "The One Where Monica Sings"],
  ["s09_e14", "The One With The Blind Dates"],
  ["s09_e15", "The One With The Mugging"],
  ["s09_e16", "The One With The Boob Job"],
  ["s09_e17", "The One With The Memorial Service"],
  ["s09_e18", "The One With The Lottery"],
  ["s09_e19", "The One With Rachel's Dream"],
  ["s09_e20", "The One With The Soap Opera Party"],
  ["s09_e21", "The One With The Fertility Test"],
  ["s09_e22", "The One With The Donor"],
  ["s09_e23", "The One In Barbados, Part 1"],
  ["s09_e24", "The One In Barbados, Part 2"],
  ["s10_e01", "The One After Joey and Rachel Kiss"],
  ["s10_e02", "The One Where Ross is Fine"],
  ["s10_e03", "The One With Ross's Tan"],
  ["s10_e04", "The One With the Cake"],
  ["s10_e05", "The One Where Rachel's Sister Baby-sits"],
  ["s10_e06", "The One With Ross's Grant"],
  ["s10_e07", "The One With the Home Study"],
  ["s10_e08", "The One With the Late Thanksgiving"],
  ["s10_e09", "The One With The Birth Mother"],
  ["s10_e10", "The One Where Chandler Gets Caught"],
  ["s10_e11", "The One Where The Stripper Cries"],
  ["s10_e12", "The One With Phoebe's Wedding"],
  ["s10_e13", "The One Where Joey Speaks French"],
  ["s10_e14", "The One With Princess Consuela"],
  ["s10_e15", "The One Where Estelle Dies"],
  ["s10_e16", "The One With Rachel's Going Away Party"],
  ["s10_e17", "The Last One, Part 1"],
  ["s10_e18", "The Last One, Part 2"],
]);
